spi.topic.consumer.name: 
mdi.topic.consumer.name:
mpi.topic.consumer.name:
hpi.topic.consumer.name:
imgi.topic.consumer.name:
spi.topic.producer.name:
mdi.topic.producer.name:
mpi.topic.producer.name:
hpi.topic.producer.name:
imgi.topic.producer.name:
spi.topic.pcount: 
mdi.topic.pcount: 
mpi.topic.pcount: 
hpi.topic.pcount: 
imgi.topic.pcount: 
apaas_bucket: 
s3_region:
brokers: